openapi: "3.0.0"

info:
  version: 1.0.0
  title: Tacktail Backend API
  description: 自宅でカクテルに挑戦するためのカクテルレシピWebサービスのバックエンドWeb APIです。

servers:
  - url: http://localhost:8080
    description: 開発用サーバー

paths:
  /users:
    post:
      tags:
        - サインアップ・ログイン
      description: 新規ユーザー登録を行う
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - password
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 20
                  example: exampleName00
                password:
                  type: string
                  format: password
                  example: examplePassword00
      responses:
        "201":
          description: 新規ユーザー登録に成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  password:
                    type: string
                    format: password
        "400":
          description: リクエストが間違い
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
