openapi: "3.0.0"

info:
  version: 1.0.0
  title: Tacktail Backend API
  description: 自宅でカクテルに挑戦するためのカクテルレシピWebサービスのバックエンドWeb APIです。

servers:
  - url: http://localhost:8080
    description: 開発用サーバー

paths:
  /login:
    post:
      tags:
        - サインアップ・ログイン
      description: ログイン処理
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - password
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 20
                password:
                  type: string
                  format: password
      responses:
        "200":
          description: ログインに成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
        "400":
          description: リクエストが間違い
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "401":
          description: 認証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /users:
    post:
      tags:
        - サインアップ・ログイン
      description: 新規ユーザー登録を行う
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - password
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 20
                password:
                  type: string
                  format: password
      responses:
        "201":
          description: 新規ユーザー登録に成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  password:
                    type: string
                    format: password
        "400":
          description: リクエストが間違い
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /auth/users:
    get:
      tags:
        - ストーリーモード
      description: ユーザー情報取得 (ストーリーモードでクリア状況の取得)
      operationId: authFindUser
      security:
        - cookieAuth: ["/loginでログインすることでヘッダーのBearerにJWTがセットされていること"]
      responses:
        "200":
          description: ユーザー情報の取得に成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  password:
                    type: string
                  story:
                    type: integer
        "401":
          description: 認証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /auth/users/story:
    post:
      tags:
        - ストーリーモード
      description: ユーザーのストーリー攻略状況を更新
      operationId: authUpdateUserStory
      security:
        - cookieAuth: ["/loginでログインすることでヘッダーのBearerにJWTがセットされていること"]
      responses:
        "201":
          description: ユーザーのストーリー攻略状況の更新に成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                  story:
                    type: integer
        "401":
          description: 認証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /cocktails/individual:
    get:
      tags:
        - カクテル
      description: カクテルIDからカクテル情報の取得
      operationId: getCocktail
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: カクテルIDからカクテル情報の取得に成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  image:
                    type: string
                  materials:
                    type: array
                    description: カクテルに用いる材料の配列
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        amount:
                          type: integer
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /auth/cocktails/individual:
    get:
      tags:
        - カクテル
      description: 認証付きでカクテルIDからカクテル情報の取得
      operationId: getCocktailWithAuth
      security:
        - cookieAuth: ["/loginでログインすることでBearerにJWTがセットされていること"]
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: カクテルIDからカクテル情報の取得に成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  image:
                    type: string
                  materials:
                    type: array
                    description: カクテルに用いる材料の配列
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        amount:
                          type: integer
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /cocktails/list:
    get:
      tags:
        - カクテル
      description: カクテル一覧の取得
      operationId: getCocktails
      parameters:
      - in: query
        name: materials
        required: false
        schema:
          type: string
      responses:
        "200":
          description: カクテル一覧の取得に成功
          content:
            application/json:
              schema:
                type: array
                description: カクテルの配列
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                    image:
                      type: string
                    materials:
                      type: array
                      description: 材料の配列
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          description:
                            type: string
                          amount:
                            type: integer
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /auth/cocktails/list:
    get:
      tags:
        - カクテル
      description: 認証ユーザーによるカクテル一覧の取得
      operationId: getCocktailsByAuth
      security:
        - cookieAuth: ["/loginでログインすることでBearerにJWTがセットされていること"]
      parameters:
      - in: query
        name: materials
        description: materials={材料ID}の形式で取得するカクテル一覧にフィルターを付けられる
        required: false
        schema:
          type: string
      responses:
        "200":
          description: カクテル一覧の取得に成功
          content:
            application/json:
              schema:
                type: array
                description: カクテルの配列
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                    image:
                      type: string
                    materials:
                      type: array
                      description: カクテルの配列
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          description:
                            type: string
                          amount:
                            type: integer
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /auth/cocktail_images:
    post:
      tags:
        - カクテル画像
      description: 認証ユーザーによるカクテル画像パスの保存
      operationId: saveCocktailImageWithAuth
      security:
        - cookieAuth: ["/loginでログインすることでBearerにJWTがセットされていること"]
      parameters:
      - in: query
        name: materials
        description: materials={材料ID}の形式で取得するカクテル一覧にフィルターを付けられる
        required: false
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - cocktail_id
                - image
              properties:
                name:
                  type: string
                cocktail_id:
                  type: string
                image:
                  type: string
      responses:
        "201":
          description: カクテル画像パスの保存に成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  image_id:
                    type: string
                  user_id:
                    type: string
                  cocktail_id:
                    type: string
                  image:
                    type: string
        "400":
          description: リクエストが間違い
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  securitySchemes:  # 認証が必要なエンドポイントに付加
    Bearer:
      description: BearerでのJWT認証
      type: http
      scheme: bearer
